"""Initial schema

Revision ID: 131c110a6bc6
Revises: 
Create Date: 2026-08-04 23:04:30.288282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131c110a6bc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('route_number', sa.String(), nullable=False),
    sa.Column('operator', sa.Enum('APSRTC', 'TSRTC', 'TNSTC', 'KSRTC', name='busoperator'), nullable=False),
    sa.Column('bus_type', sa.Enum('ORDINARY', 'EXPRESS', 'SUPER_LUXURY', 'SLEEPER', name='bustype'), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bus_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_routes_route_number'), ['route_number'], unique=False)

    op.create_table('bus_stops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('operator', sa.Enum('APSRTC', 'TSRTC', 'TNSTC', 'KSRTC', name='busoperator'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bus_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_stops_code'), ['code'], unique=True)

    op.create_table('cached_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key_hash', sa.String(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cached_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_routes_cache_key_hash'), ['cache_key_hash'], unique=True)

    op.create_table('dataset_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_number', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATING', 'VALIDATED', 'APPLYING', 'APPLIED', 'GRAPH_BUILDING', 'ACTIVE', 'SUPERSEDED', 'ROLLED_BACK', 'REJECTED', name='datasetstatus'), nullable=False),
    sa.Column('graph_stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_hash', sa.String(), nullable=False),
    sa.Column('ratings', sa.JSON(), nullable=False),
    sa.Column('would_recommend', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journey_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journey_feedback_route_hash'), ['route_hash'], unique=False)

    op.create_table('route_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_hash', sa.String(), nullable=False),
    sa.Column('times_recommended', sa.Integer(), nullable=False),
    sa.Column('times_selected', sa.Integer(), nullable=False),
    sa.Column('times_redirected', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_statistics_route_hash'), ['route_hash'], unique=True)

    op.create_table('scoring_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.Enum('DEFAULT', 'WOMEN', 'SENIOR', 'STUDENT', 'FAMILY', name='travelmode'), nullable=False),
    sa.Column('travel_time_weight', sa.Float(), nullable=False),
    sa.Column('waiting_time_weight', sa.Float(), nullable=False),
    sa.Column('transfers_weight', sa.Float(), nullable=False),
    sa.Column('cost_weight', sa.Float(), nullable=False),
    sa.Column('availability_weight', sa.Float(), nullable=False),
    sa.Column('comfort_weight', sa.Float(), nullable=False),
    sa.Column('safety_weight', sa.Float(), nullable=False),
    sa.Column('reliability_weight', sa.Float(), nullable=False),
    sa.Column('walking_distance_weight', sa.Float(), nullable=False),
    sa.Column('arrival_penalty_weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mode')
    )
    op.create_table('stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('station_type', sa.Enum('MAJOR_JUNCTION', 'JUNCTION', 'REGULAR', 'HALT', name='stationtype'), nullable=False),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_code'), ['code'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('train_routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('train_number', sa.String(), nullable=False),
    sa.Column('train_name', sa.String(), nullable=False),
    sa.Column('train_type', sa.Enum('EXPRESS', 'SUPERFAST', 'MAIL', 'PASSENGER', 'RAJDHANI', 'SHATABDI', 'GARIB_RATH', 'LOCAL', name='traintype'), nullable=False),
    sa.Column('runs_on', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('train_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_train_routes_train_number'), ['train_number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('preferred_mode', sa.Enum('DEFAULT', 'WOMEN', 'SENIOR', 'STUDENT', 'FAMILY', name='travelmode'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bus_stops_sequence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_route_id', sa.String(), nullable=False),
    sa.Column('bus_stop_id', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('times', sa.String(), nullable=True),
    sa.Column('fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['bus_route_id'], ['bus_routes.id'], ),
    sa.ForeignKeyConstraint(['bus_stop_id'], ['bus_stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_version_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nearby_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('bus_stop_id', sa.String(), nullable=True),
    sa.Column('connected_station_id', sa.String(), nullable=True),
    sa.Column('connected_bus_stop_id', sa.String(), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('walking_time_minutes', sa.Integer(), nullable=False),
    sa.Column('transfer_type', sa.Enum('STATION_TO_STATION', 'STATION_TO_BUS', 'BUS_TO_STATION', 'BUS_TO_BUS', name='transfertype'), nullable=False),
    sa.ForeignKeyConstraint(['bus_stop_id'], ['bus_stops.id'], ),
    sa.ForeignKeyConstraint(['connected_bus_stop_id'], ['bus_stops.id'], ),
    sa.ForeignKeyConstraint(['connected_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('from_code', sa.String(), nullable=False),
    sa.Column('to_code', sa.String(), nullable=False),
    sa.Column('route_data', sa.JSON(), nullable=False),
    sa.Column('is_favourite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_routes_session_id'), ['session_id'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('from_code', sa.String(), nullable=False),
    sa.Column('to_code', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_history_session_id'), ['session_id'], unique=False)

    op.create_table('station_popularity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('search_counts', sa.Integer(), nullable=False),
    sa.Column('footfall', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_safety',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('cctv', sa.Boolean(), nullable=False),
    sa.Column('waiting_room', sa.Boolean(), nullable=False),
    sa.Column('lighting', sa.Enum('WELL_LIT', 'MODERATE', 'POOR', 'UNKNOWN', name='lightingquality'), nullable=False),
    sa.Column('crowd', sa.Enum('LOW', 'MODERATE', 'HIGH', 'UNKNOWN', name='crowdlevel'), nullable=False),
    sa.Column('community_rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_fares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_route_id', sa.String(), nullable=False),
    sa.Column('from_station_id', sa.String(), nullable=False),
    sa.Column('to_station_id', sa.String(), nullable=False),
    sa.Column('travel_class', sa.Enum('GENERAL', 'SLEEPER', 'AC_3', 'AC_2', 'AC_1', name='travelclass'), nullable=False),
    sa.Column('fare_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['train_route_id'], ['train_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_route_id', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=True),
    sa.Column('departure_time', sa.String(), nullable=True),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('distance_from_origin', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['train_route_id'], ['train_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_stops')
    op.drop_table('train_fares')
    op.drop_table('station_safety')
    op.drop_table('station_popularity')
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_session_id'))

    op.drop_table('search_history')
    with op.batch_alter_table('saved_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_routes_session_id'))

    op.drop_table('saved_routes')
    op.drop_table('nearby_connections')
    op.drop_table('import_logs')
    op.drop_table('bus_stops_sequence')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('train_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_train_routes_train_number'))

    op.drop_table('train_routes')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_code'))

    op.drop_table('stations')
    op.drop_table('scoring_weights')
    with op.batch_alter_table('route_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_statistics_route_hash'))

    op.drop_table('route_statistics')
    with op.batch_alter_table('journey_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journey_feedback_route_hash'))

    op.drop_table('journey_feedback')
    op.drop_table('dataset_versions')
    with op.batch_alter_table('cached_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cached_routes_cache_key_hash'))

    op.drop_table('cached_routes')
    with op.batch_alter_table('bus_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_stops_code'))

    op.drop_table('bus_stops')
    with op.batch_alter_table('bus_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_routes_route_number'))

    op.drop_table('bus_routes')
    # ### end Alembic commands ###
